a=int(input())
hun=int(a/100)
hun_extra=int(a%100)
fifty=int(hun_extra/50)
fifty_extra=int(hun_extra%50)
twenty=int(fifty_extra/20)
twenty_extra=int(fifty_extra%20)
ten=int(twenty_extra/10)
ten_extra=int(twenty_extra%10)
five=int(ten_extra/5)
five_extra=int(ten_extra%5)
two=int(five_extra/2)
two_extra=int(five_extra%2)
one=int(two_extra/1)

print("%d"%a)
print("%d nota(s) de R$ 100,00"%hun)
print("%d nota(s) de R$ 50,00"%fifty)
print("%d nota(s) de R$ 20,00"%twenty)
print("%d nota(s) de R$ 10,00"%ten)
print("%d nota(s) de R$ 5,00"%five)
print("%d nota(s) de R$ 2,00"%two)
print("%d nota(s) de R$ 1,00"%one)
