a=float(input())
hun=float(a/100)
hun_extra=float(a%100)
fifty=float(hun_extra/50)
fifty_extra=float(hun_extra%50)
twenty=float(fifty_extra/20)
twenty_extra=float(fifty_extra%20)
ten=float(twenty_extra/10)
ten_extra=float(twenty_extra%10)
five=float(ten_extra/5)
five_extra=float(ten_extra%5)
two=float(five_extra/2)
two_extra=float(five_extra%2)
one=float(two_extra/1)
one_extra=float(two_extra%1)
point_fifty=float(one_extra/.50)
point_fifty_extra=float(one_extra%.50)
point_twenty_five=float(point_fifty_extra/.25)
point_twenty_five_extra=float(point_fifty_extra%.25)
point_ten=float(point_twenty_five_extra/.10)
point_ten_extra=float(point_twenty_five_extra%.10)
point_five=float(point_ten_extra/.05)
point_five_extra=float(point_ten_extra%.05)
point_one=float(point_five_extra/.01)

print("%s"%'NOTAS:')
print("%d nota(s) de R$ 100.00"%hun)
print("%d nota(s) de R$ 50.00"%fifty)
print("%d nota(s) de R$ 20.00"%twenty)
print("%d nota(s) de R$ 10.00"%ten)
print("%d nota(s) de R$ 5.00"%five)
print("%d nota(s) de R$ 2.00"%two)
print("%s"%'MOEDAS:')
print("%d moeda(s) de R$ 1.00"%one)
print("%d moeda(s) de R$ 0.50"%point_fifty)
print("%d moeda(s) de R$ 0.25"%point_twenty_five)
print("%d moeda(s) de R$ 0.10"%point_ten)
print("%d moeda(s) de R$ 0.05"%point_five)
print("%.f moeda(s) de R$ 0.01"%point_one)
